### ISSUE TITLE
Request: link to diff and options to log

### ISSUE THREAD

**Issue by tkf** [magit/org-magit#3]
It would be nice to have links such as the following.  I guess you need to %-encode whitespace, though.

```
magit:/path/to/repo::log --since="Jan 14 2013"
magit:/path/to/repo::diff REV-1 REV-2
```

**Comment by tarsius** [comment]
I have written a successor for this library; [`orgit`](https://github.com/magit/orgit). It also doesn't currently support diffs but I intend to write that eventually. You may open a new issue there, that might or might not speedup the process :-) But I don't think anyone is going to implement this here, so I am closing this.
